import { useEffect, useMemo, useRef, useState } from 'react';
import { formatDistanceToNow } from 'date-fns';
import Sidebar from './components/Sidebar'; import AgentPipeline from './components/AgentPipeline'; import ImpactPanel from './components/ImpactPanel'; import DiffViewer from './components/DiffViewer'; import ChangeHistory from './components/ChangeHistory'; import EmptyState from './components/EmptyState';
import { getHistory, getLatestChangeResult, getUrls, removeUrlData, saveUrls } from './lib/storage'; import { createMonitorScheduler, getMonitorInterval, getNextCheckAt } from './lib/monitorScheduler'; import { exportHistoryAsMarkdown } from './lib/report'; import { useArgusCheck } from './hooks/useArgusCheck'; import { useNotifications } from './hooks/useNotifications';

const idle = { fetcher: 'IDLE', differ: 'IDLE', analyst: 'IDLE', notifier: 'IDLE' };
const developmentIntervalOverride = import.meta.env.DEV && Number(import.meta.env.VITE_ARGUS_SCHEDULER_TEST_MS) > 0 ? Number(import.meta.env.VITE_ARGUS_SCHEDULER_TEST_MS) : undefined;
export default function App() {
  const initialSelectedId = getUrls()[0]?.id || null; const initialResult = getLatestChangeResult(initialSelectedId);
  const [urls, setUrls] = useState(getUrls); const [selectedId, setSelectedId] = useState(initialSelectedId); const [analysis, setAnalysis] = useState(initialResult?.analysis || null); const [diff, setDiff] = useState(initialResult?.diff || null); const [message, setMessage] = useState('Select a URL and run a check.'); const [error, setError] = useState(null); const [now, setNow] = useState(() => Date.now()); const { permission, requestPermission, send } = useNotifications(); const selected = useMemo(() => urls.find((item) => item.id === selectedId), [urls, selectedId]); const history = selectedId ? getHistory(selectedId) : []; const urlsRef = useRef(urls); const schedulerRef = useRef(createMonitorScheduler());
  useEffect(() => { urlsRef.current = urls; }, [urls]);
  const persist = (update) => setUrls((current) => { const next = typeof update === 'function' ? update(current) : update; saveUrls(next); return next; });
  const updateStatus = (status, at = new Date().toISOString(), target) => { if (status === 'CHECKING' && target?.id === selectedId) setError(null); persist((current) => current.map((item) => item.id === target?.id ? { ...item, status, lastCheckedAt: at, ...(status === 'CHANGE_DETECTED' ? { lastChangeAt: at } : {}) } : item)); };
  const onComplete = (result) => { if (result.urlConfig?.id !== selectedId) return; if (result.error) { setError(result.error); setMessage('A pipeline agent needs attention.'); return; } if (result.baseline) { setMessage('Baseline captured. ARGUS will analyze the next change.'); } else if (!result.changed) { setMessage('No meaningful change detected.'); } else { setAnalysis(result.analysis); setDiff(result.diff); setMessage('Change detected and analyzed.'); } };
  const { agentStatuses, runCheck, isRunning } = useArgusCheck({ urlConfig: selected, onComplete, onStatus: updateStatus, notify: send });
  const runCheckRef = useRef(runCheck); useEffect(() => { runCheckRef.current = runCheck; }, [runCheck]);
  useEffect(() => { const tick = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(tick); }, []);
  const monitorConfigJson = JSON.stringify(urls.map(({ id, url, monitorInterval, filterNoise, nextCheckAt, lastCheckedAt, addedAt }) => ({ id, url, monitorInterval, filterNoise, nextCheckAt, lastCheckedAt: nextCheckAt ? undefined : lastCheckedAt, addedAt })));
  useEffect(() => { const scheduler = schedulerRef.current; const scheduledUrls = JSON.parse(monitorConfigJson); scheduler.cancelAll(); scheduledUrls.forEach((item) => { const interval = getMonitorInterval(item.monitorInterval, developmentIntervalOverride); if (!interval) return; scheduler.schedule(item.id, getNextCheckAt(item, interval), () => { const target = urlsRef.current.find((url) => url.id === item.id); if (!target) return; const nextCheckAt = new Date(Date.now() + getMonitorInterval(target.monitorInterval, developmentIntervalOverride)).toISOString(); setUrls((current) => { const next = current.map((url) => url.id === target.id ? { ...url, nextCheckAt } : url); saveUrls(next); return next; }); runCheckRef.current(target); }); }); return () => scheduler.cancelAll(); }, [monitorConfigJson]);
  const selectUrl = (id) => { const latest = id ? getLatestChangeResult(id) : null; setSelectedId(id); setAnalysis(latest?.analysis || null); setDiff(latest?.diff || null); setError(null); };
  const addUrl = (url, label, monitorInterval, filterNoise) => { const item = { id: crypto.randomUUID(), url, label: label.trim(), addedAt: new Date().toISOString(), status: 'IDLE', monitorInterval, filterNoise }; persist((current) => [...current, item]); selectUrl(item.id); setMessage('URL added. Capture a baseline when you are ready.'); };
  const updateUrl = (id, patch) => persist((current) => current.map((item) => { if (item.id !== id) return item; const next = { ...item, ...patch }; if (Object.hasOwn(patch, 'monitorInterval')) { const interval = getMonitorInterval(next.monitorInterval, developmentIntervalOverride); next.nextCheckAt = interval ? new Date(Date.now() + interval).toISOString() : null; } return next; }));
  const removeUrl = (id) => { removeUrlData(id); const next = urls.filter((item) => item.id !== id); persist(next); if (selectedId === id) selectUrl(next[0]?.id || null); };
  const nextCheck = (item) => { const interval = getMonitorInterval(item.monitorInterval, developmentIntervalOverride); if (!interval) return 'manual'; const seconds = Math.max(0, Math.ceil((getNextCheckAt(item, interval) - now) / 1000)); return seconds === 0 ? 'due now' : `in ${seconds < 60 ? `${seconds}s` : `${Math.ceil(seconds / 60)}m`}`; };
  return <main className="min-h-screen bg-bg text-text-primary lg:flex"><Sidebar urls={urls} selectedId={selectedId} onSelect={selectUrl} onAdd={addUrl} onRemove={removeUrl} onCheck={runCheck} onUpdate={updateUrl} isRunning={isRunning} nextCheck={nextCheck} /><div className="min-w-0 flex-1"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4 lg:px-8"><div><p className="panel-label">ARGUS surveillance console</p><p className="mt-1 text-sm text-text-secondary">{selected ? selected.label || selected.url : 'No active target'}</p>{selected?.lastChangeAt && <p className="mt-1 text-xs text-violet-300">Last change detected {formatDistanceToNow(new Date(selected.lastChangeAt), { addSuffix: true })}</p>}</div><div className="flex gap-2"><button disabled={!selected || !history.length} className="button-secondary" onClick={() => exportHistoryAsMarkdown(selected, history)}>Export Markdown</button><button className="button-secondary" onClick={requestPermission}>{permission === 'granted' ? 'Notifications enabled' : 'Enable notifications'}</button></div></header><div className="mx-auto max-w-6xl space-y-5 p-5 lg:p-8">{!selected ? <EmptyState onAdd={() => document.querySelector('.button-primary')?.click()} /> : <><AgentPipeline statuses={agentStatuses || idle} />{error ? <div className="flex flex-wrap items-center justify-between gap-3 border border-red-900 bg-red-950/30 p-3 text-sm text-red-200"><span>{error}</span><button className="button-secondary" disabled={isRunning} onClick={() => runCheck(selected)}>Retry check</button></div> : <p className={`border px-3 py-2 text-sm ${message.includes('detected') ? 'border-green-900 bg-green-950/20 text-green-300' : 'border-border bg-surface text-text-secondary'}`}>{message}</p>}<div className="grid gap-5 xl:grid-cols-2"><div className="space-y-5"><ImpactPanel analysis={analysis} /><DiffViewer diff={diff} /></div><ChangeHistory history={history} /></div></>}</div></div></main>;
}
