import { useEffect, useMemo, useRef, useState } from 'react';
import { formatDistanceToNow } from 'date-fns';
import Sidebar from './components/Sidebar'; import AgentPipeline from './components/AgentPipeline'; import ImpactPanel from './components/ImpactPanel'; import DiffViewer from './components/DiffViewer'; import ChangeHistory from './components/ChangeHistory'; import EmptyState from './components/EmptyState';
import { getSelectedUrl, getUrls, saveSelectedUrl, saveUrls } from './lib/storage'; import { createMonitorScheduler, getMonitorInterval, getNextCheckAt } from './lib/monitorScheduler'; import { exportHistoryAsMarkdown } from './lib/report'; import { useArgusCheck } from './hooks/useArgusCheck'; import { useNotifications } from './hooks/useNotifications';
const idle = { fetcher: 'IDLE', differ: 'IDLE', analyst: 'IDLE', notifier: 'IDLE' };
const developmentIntervalOverride = import.meta.env.DEV && Number(import.meta.env.VITE_ARGUS_SCHEDULER_TEST_MS) > 0 ? Number(import.meta.env.VITE_ARGUS_SCHEDULER_TEST_MS) : undefined;
const latestResult = (target) => {
  const event = target?.history?.find((entry) => entry.summary && entry.severity);
  if (!event) return { analysis: null, diff: null };
  const displayDiffs = event.diffSnippet.split('\n').filter(Boolean).map((line) => [line[0] === '+' ? 1 : line[0] === '-' ? -1 : 0, line[0] === '+' || line[0] === '-' || line[0] === ' ' ? line.slice(1) : line]);
  return { analysis: { summary: event.summary, severity: event.severity, areas_affected: event.areas_affected || [], recommended_action: event.recommended_action || '', reasoning: event.reasoning || '' }, diff: displayDiffs.length ? { displayDiffs, addedCount: event.deterministicMetrics?.added_characters || 0, removedCount: event.deterministicMetrics?.removed_characters || 0 } : null };
};
export default function App() {
  const [urls, setUrls] = useState(getUrls); const [selectedId, setSelectedId] = useState(() => getUrls()[0]?.id || null); const [messagesByTarget, setMessagesByTarget] = useState({}); const [errorsByTarget, setErrorsByTarget] = useState({}); const [now, setNow] = useState(() => Date.now()); const { permission, requestPermission, send } = useNotifications(); const selected = useMemo(() => urls.find((item) => item.id === selectedId), [urls, selectedId]); const selectedKey = selected?.clientKey || selected?.id; const message = selectedKey ? messagesByTarget[selectedKey] || 'Select a URL and run a check.' : 'Select a URL and run a check.'; const error = selectedKey ? errorsByTarget[selectedKey] || null : null; const restoredResult = useMemo(() => latestResult(selected), [selected]); const history = selected?.history || []; const urlsRef = useRef(urls); const schedulerRef = useRef(createMonitorScheduler());
  const persistCache = (update) => setUrls((current) => { const next = typeof update === 'function' ? update(current) : update; saveUrls(next); return next; });
  const setTargetMessage = (target, value) => { const key = target?.clientKey || target?.id; if (key) setMessagesByTarget((all) => ({ ...all, [key]: value })); };
  const setTargetError = (target, value) => { const key = target?.clientKey || target?.id; if (key) setErrorsByTarget((all) => ({ ...all, [key]: value })); };
  useEffect(() => { fetch('/api/monitor/targets').then((res) => res.ok ? res.json() : null).then((data) => { if (!data) return; setUrls((legacy) => { const pending = legacy.filter((item) => !data.targets.some((target) => target.url === item.url)); const merged = [...data.targets.map((target) => ({ ...target, clientKey: target.id })), ...pending]; const rememberedUrl = getSelectedUrl(); saveUrls(pending); setSelectedId((current) => merged.find((item) => item.id === current)?.id || merged.find((item) => item.url === rememberedUrl)?.id || merged[0]?.id || null); return merged; }); }).catch(() => {}); }, []);
  useEffect(() => { urlsRef.current = urls; }, [urls]); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const updateStatus = (status, at, target) => persistCache((current) => current.map((item) => item.id === target?.id || item.url === target?.url ? { ...item, status, lastCheckedAt: at, ...(status === 'CHANGE_DETECTED' ? { lastChangeAt: at } : {}) } : item));
  const onComplete = (result) => { const updated = result.urlConfig; if (result.error) { setTargetError(updated, result.error); setTargetMessage(updated, 'A pipeline agent needs attention.'); return; } setTargetError(updated, null); if (result.target) { const wasSelected = updated.id === selectedId || updated.url === selected?.url; persistCache((current) => current.map((item) => item.id === updated.id || item.url === updated.url ? { ...item, ...updated, status: result.changed ? 'CHANGE_DETECTED' : 'NO_CHANGE', history: result.event ? [result.event, ...(item.history || [])] : item.history || [] } : item)); if (wasSelected) { setSelectedId(updated.id); saveSelectedUrl(updated.url); } } if (result.baseline) setTargetMessage(updated, 'Authoritative baseline captured. ARGUS will analyze the next change.'); else if (!result.changed) setTargetMessage(updated, 'No meaningful change detected.'); else setTargetMessage(updated, 'Change detected and analyzed.'); };
  const { agentStatuses, runCheck, isRunning } = useArgusCheck({ urlConfig: selected, onComplete, onStatus: updateStatus, notify: send }); const runCheckRef = useRef(runCheck); useEffect(() => { runCheckRef.current = runCheck; }, [runCheck]);
  const config = JSON.stringify(urls.map(({ id, url, monitorInterval, filterNoise, nextCheckAt, lastCheckedAt, addedAt }) => ({ id, url, monitorInterval, filterNoise, nextCheckAt, lastCheckedAt, addedAt })));
  useEffect(() => { const scheduler = schedulerRef.current; scheduler.cancelAll(); JSON.parse(config).forEach((item) => { const interval = getMonitorInterval(item.monitorInterval, developmentIntervalOverride); if (!interval) return; scheduler.schedule(item.id, getNextCheckAt(item, interval), () => { const target = urlsRef.current.find((entry) => entry.id === item.id); if (!target) return; persistCache((current) => current.map((entry) => entry.id === target.id ? { ...entry, nextCheckAt: new Date(Date.now() + interval).toISOString() } : entry)); runCheckRef.current(target); }); }); return () => scheduler.cancelAll(); }, [config]);
  const selectUrl = (id) => { const item = urls.find((entry) => entry.id === id); setSelectedId(id); saveSelectedUrl(item?.url || null); };
  const addUrl = (url, label, monitorInterval, filterNoise) => { const id = crypto.randomUUID(); const item = { id, clientKey: id, url, label: label.trim(), addedAt: new Date().toISOString(), status: 'IDLE', monitorInterval, filterNoise, history: [] }; persistCache((current) => [...current, item]); setSelectedId(id); saveSelectedUrl(url); setTargetMessage(item, 'URL added. Capture an authoritative baseline when you are ready.'); };
  const updateUrl = (id, patch) => persistCache((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item));
  const removeUrl = (id) => { const item = urls.find((entry) => entry.id === id); if (item?.siteId) fetch('/api/monitor/targets', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ siteId: item.siteId }) }); const next = urls.filter((item) => item.id !== id); persistCache(next); if (selectedId === id) selectUrl(next[0]?.id || null); };
  const nextCheck = (item) => { const interval = getMonitorInterval(item.monitorInterval, developmentIntervalOverride); if (!interval) return 'manual'; const seconds = Math.max(0, Math.ceil((getNextCheckAt(item, interval) - now) / 1000)); return seconds === 0 ? 'due now' : `in ${seconds < 60 ? `${seconds}s` : `${Math.ceil(seconds / 60)}m`}`; };
  return <main className="min-h-screen bg-bg text-text-primary lg:flex"><Sidebar urls={urls} selectedId={selectedId} onSelect={selectUrl} onAdd={addUrl} onRemove={removeUrl} onCheck={runCheck} onUpdate={updateUrl} isRunning={isRunning} nextCheck={nextCheck} /><div className="min-w-0 flex-1"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4 lg:px-8"><div><p className="panel-label">ARGUS surveillance console</p><p className="mt-1 text-sm text-text-secondary">{selected ? selected.label || selected.url : 'No active target'}</p>{selected?.lastChangeAt && <p className="mt-1 text-xs text-violet-300">Last change detected {formatDistanceToNow(new Date(selected.lastChangeAt), { addSuffix: true })}</p>}</div><div className="flex gap-2"><button disabled={!selected || !history.length} className="button-secondary" onClick={() => exportHistoryAsMarkdown(selected, history)}>Export Markdown</button><button className="button-secondary" onClick={requestPermission}>{permission === 'granted' ? 'Notifications enabled' : 'Enable notifications'}</button></div></header><div className="mx-auto max-w-6xl space-y-5 p-5 lg:p-8">{!selected ? (urls.length === 0 ? <EmptyState onAdd={() => document.querySelector('.button-primary')?.click()} /> : <section className="panel"><p className="panel-label">Choose a watched URL</p><p className="mt-3 text-sm text-text-secondary">Select a target from the watchlist to view its surveillance console.</p></section>) : <><AgentPipeline statuses={agentStatuses || idle} />{error ? <div className="flex flex-wrap items-center justify-between gap-3 border border-red-900 bg-red-950/30 p-3 text-sm text-red-200"><span>{error}</span><button className="button-secondary" disabled={isRunning} onClick={() => runCheck(selected)}>Retry check</button></div> : <p className={`border px-3 py-2 text-sm ${message.includes('detected') ? 'border-green-900 bg-green-950/20 text-green-300' : 'border-border bg-surface text-text-secondary'}`}>{message}</p>}<div className="grid gap-5 xl:grid-cols-2"><div className="space-y-5"><ImpactPanel analysis={restoredResult.analysis} /><DiffViewer diff={restoredResult.diff} /></div><ChangeHistory history={history} /></div></>}</div></div></main>;
}
